sudo: false
language: node_js
node_js:
- 12
script:
- npm run lint
before_install:
- openssl aes-256-cbc -K $encrypted_b4b6ddef1958_key -iv $encrypted_b4b6ddef1958_iv
  -in ftppass.json.enc -out ftppass.json -d
after_script:
- npm run deploy
